version: "3.9"

services:
  fail2ban_flask:
    container_name: flask_fail2ban
    build: .
    image: flask_fail2ban:1.0.7
    volumes:
      - app:/app
    ports:
      - '5000:5000'
    restart: always
    networks:
      - backend
    command: ["python", "app.py"]

volumes:
  app:

networks:
  backend:
    name: tn_backend
