version: "3.9"

services:
  fail2ban_flask:
    container_name: fail2ban_flask
    build: .
    image: fail2ban-flask:1.0.5
    volumes:
      - app:/app
    ports:
      - '5000:5000'
    restart: always
    networks:
      - backend
    command: ["python", "app.py"]

volumes:
  app:

networks:
  backend:
    name: tn_backend
